name: Node.js CI/CD Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v3

      - name: 安装 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 安装依赖
        run: npm install

  deploy:
    needs: build  # 只有 build 任务成功后才执行
    runs-on: ubuntu-latest
    steps:
      - name: 部署到服务器
        uses: easingthemes/ssh-deploy@v2.1.1
        with:
          # 私钥
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          script: |
            cd /var/www/demo
            git pull origin main
            npm install
            pm2 restart server
